name: Deploy Fullstack App to Heroku

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # specify your node version

      - name: Install dependencies for backend
        run: |
          npm install

      - name: Install dependencies for frontend
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build  # assuming you have a build script in your package.json

      - name: Debug frontend build output
        run: |
          echo "Listing contents of client directory:"
          ls client
          echo "Listing contents of client/dist directory:"
          ls client/dist

      - name: Check frontend build output
        run: |
          if [ ! -d "client/dist" ]; then echo "Frontend build failed. No 'client/dist' directory found."; exit 1; fi

      - name: Move frontend build to backend
        run: |
          cp -r client/dist/* api/public/

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_BACKEND }}
        run: |
          cd api
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME_BACKEND }}
          git add .
          git commit -m "Deploy to Heroku"
          git push heroku main
